// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Curry                      = require("bs-platform/lib/js/curry.js");
var React                      = require("react");
var Glamor                     = require("typed-glamor/src/Glamor.bs.js");
var ReasonReact                = require("reason-react/src/ReasonReact.js");
var StyleContainer$StyledReact = require("../src/StyleContainer.bs.js");

function text(prim) {
  return prim;
}

function css() {
  return /* :: */[
          Glamor.border3(Glamor.thick, Glamor.solid, Glamor.green),
          /* [] */0
        ];
}

var Root = StyleContainer$StyledReact.Make(/* module */[
      /* css */css,
      /* element */"div"
    ]);

var Stateless = StyleContainer$StyledReact.stateless(/* None */0, /* :: */[
      Glamor.border3(Glamor.thick, Glamor.solid, Glamor.blue),
      /* :: */[
        Glamor.select("& *", /* :: */[
              Glamor.border3(Glamor.thin, Glamor.dashed, Glamor.green),
              /* :: */[
                Glamor.hover(/* :: */[
                      Glamor.borderColor(Glamor.red),
                      /* [] */0
                    ]),
                /* [] */0
              ]
            ]),
        /* [] */0
      ]
    ]);

var Styles = /* module */[
  /* Root */Root,
  /* Stateless */Stateless
];

var component = ReasonReact.statelessComponent("Page");

function make(message, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return ReasonReact.element(/* None */0, /* None */0, Curry._1(Stateless[/* make */0], /* array */[
                      React.createElement("div", undefined, message),
                      React.createElement("div", undefined, "World!")
                    ]));
    });
  return newrecord;
}

exports.text      = text;
exports.Styles    = Styles;
exports.component = component;
exports.make      = make;
/* Root Not a pure module */
