// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var $$Array                    = require("bs-platform/lib/js/array.js");
var Block                      = require("bs-platform/lib/js/block.js");
var Curry                      = require("bs-platform/lib/js/curry.js");
var React                      = require("react");
var Caml_obj                   = require("bs-platform/lib/js/caml_obj.js");
var ReasonReact                = require("reason-react/src/ReasonReact.js");
var TypedGlamor                = require("typed-glamor/src/TypedGlamor.bs.js");
var StyleContainer$StyledReact = require("../src/StyleContainer.bs.js");

function text(prim) {
  return prim;
}

var Stateless = StyleContainer$StyledReact.stateless(/* None */0, /* :: */[
      TypedGlamor.border3(TypedGlamor.thin, TypedGlamor.solid, TypedGlamor.hex(3822)),
      /* [] */0
    ]);

function css(isSelected) {
  return /* :: */[
          TypedGlamor.borderBottom3(TypedGlamor.thin, TypedGlamor.dashed, TypedGlamor.hex(3822)),
          /* :: */[
            TypedGlamor.padding2(TypedGlamor.em(1), TypedGlamor.em(2)),
            /* :: */[
              TypedGlamor.background(isSelected !== 0 ? TypedGlamor.whitesmoke : TypedGlamor.$$null),
              /* :: */[
                TypedGlamor.hover(/* :: */[
                      TypedGlamor.background(TypedGlamor.antiquewhite),
                      /* [] */0
                    ]),
                /* [] */0
              ]
            ]
          ]
        ];
}

var Fruit = StyleContainer$StyledReact.Make(/* module */[
      /* css */css,
      /* element */"div"
    ]);

var Styles = /* module */[
  /* Stateless */Stateless,
  /* Fruit */Fruit
];

var fruit = /* array */[
  "apple",
  "banana",
  "pear",
  "mango",
  "coconut"
];

var component = ReasonReact.statelessComponent("Fruit");

function make(name, isSelected, onSelect, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return ReasonReact.element(/* None */0, /* None */0, Curry._2(Fruit[/* make */1], isSelected, /* array */[React.createElement("div", {
                            onClick: (function () {
                                return Curry._1(onSelect, /* () */0);
                              })
                          }, name)]));
    });
  return newrecord;
}

var Fruit$1 = /* module */[
  /* component */component,
  /* make */make
];

var component$1 = ReasonReact.reducerComponent("Page");

function make$1(_, _$1) {
  var newrecord = component$1.slice();
  newrecord[/* render */9] = (function (param) {
      var state = param[/* state */2];
      var reduce = param[/* reduce */1];
      return ReasonReact.element(/* None */0, /* None */0, Curry._1(Stateless[/* make */0], /* array */[$$Array.map((function (name) {
                              return ReasonReact.element(/* None */0, /* None */0, make(name, Caml_obj.caml_equal(/* Some */[name], state[/* selected */0]), Curry._1(reduce, (function () {
                                                    return /* Select */[name];
                                                  })), /* array */[]));
                            }), fruit)]));
    });
  newrecord[/* initialState */10] = (function () {
      return /* record */[/* selected : None */0];
    });
  newrecord[/* reducer */12] = (function (action, _) {
      return /* Update */Block.__(0, [/* record */[/* selected : Some */[action[0]]]]);
    });
  return newrecord;
}

exports.text      = text;
exports.Styles    = Styles;
exports.fruit     = fruit;
exports.Fruit     = Fruit$1;
exports.component = component$1;
exports.make      = make$1;
/* Stateless Not a pure module */
