// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var $$String = require("bs-platform/lib/js/string.js");
var Js_dict  = require("bs-platform/lib/js/js_dict.js");

var Value = /* module */[];

function join(vs) {
  return $$String.concat(", ", vs);
}

var Values = /* module */[/* join */join];

var Declaration = /* module */[];

var toDict = Js_dict.fromList;

var Declarations = /* module */[/* toDict */toDict];

var Selector = /* module */[];

exports.Value        = Value;
exports.Values       = Values;
exports.Declaration  = Declaration;
exports.Declarations = Declarations;
exports.Selector     = Selector;
/* Js_dict Not a pure module */
