// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Curry       = require("bs-platform/lib/js/curry.js");
var Glamor      = require("typed-glamor/src/Glamor.bs.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("Style");

function make(css, $staropt$star, children) {
  var element = $staropt$star ? $staropt$star[0] : "div";
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return ReasonReact.createDomElement(element, {
                  className: css
                }, children);
    });
  return newrecord;
}

function Make(Config) {
  var component = ReasonReact.statelessComponent("Style");
  var make = function (state, children) {
    var newrecord = component.slice();
    newrecord[/* render */9] = (function () {
        return ReasonReact.createDomElement(Config[/* element */1], {
                    className: Glamor.css(Curry._1(Config[/* css */0], state))
                  }, children);
      });
    return newrecord;
  };
  return /* module */[
          /* component */component,
          /* make */make
        ];
}

function stateless($staropt$star, css) {
  var element = $staropt$star ? $staropt$star[0] : "div";
  var component = ReasonReact.statelessComponent("Style");
  var make = function (param) {
    var children = param;
    var newrecord = component.slice();
    newrecord[/* render */9] = (function () {
        return ReasonReact.createDomElement(element, {
                    className: Glamor.css(css)
                  }, children);
      });
    return newrecord;
  };
  return /* module */[/* make */make];
}

exports.component = component;
exports.make      = make;
exports.Make      = Make;
exports.stateless = stateless;
/* component Not a pure module */
