// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Glamor      = require("../src/Glamor.bs.js");
var TestHelpers = require("./TestHelpers.bs.js");

describe("margin", (function () {
        TestHelpers.testDeclaration(Glamor.margin(Glamor.auto), /* tuple */[
              "margin",
              "auto"
            ]);
        TestHelpers.testDeclaration(Glamor.margin2(Glamor.zero, Glamor.auto), /* tuple */[
              "margin",
              "0 auto"
            ]);
        TestHelpers.testDeclaration(Glamor.margin3(Glamor.pct(10), Glamor.auto, Glamor.px(45)), /* tuple */[
              "margin",
              "10% auto 45px"
            ]);
        TestHelpers.testDeclaration(Glamor.margin4(Glamor.pct(10), Glamor.auto, Glamor.px(45), Glamor.ex(2)), /* tuple */[
              "margin",
              "10% auto 45px 2ex"
            ]);
        TestHelpers.testDeclaration(Glamor.marginTop(Glamor.px(1)), /* tuple */[
              "marginTop",
              "1px"
            ]);
        TestHelpers.testDeclaration(Glamor.marginRight(Glamor.px(1)), /* tuple */[
              "marginRight",
              "1px"
            ]);
        TestHelpers.testDeclaration(Glamor.marginBottom(Glamor.px(1)), /* tuple */[
              "marginBottom",
              "1px"
            ]);
        return TestHelpers.testDeclaration(Glamor.marginLeft(Glamor.px(1)), /* tuple */[
                    "marginLeft",
                    "1px"
                  ]);
      }));

describe("padding", (function () {
        TestHelpers.testDeclaration(Glamor.padding(Glamor.px(-1)), /* tuple */[
              "padding",
              "-1px"
            ]);
        TestHelpers.testDeclaration(Glamor.padding2(Glamor.zero, Glamor.pct(50)), /* tuple */[
              "padding",
              "0 50%"
            ]);
        TestHelpers.testDeclaration(Glamor.padding3(Glamor.pct(10), Glamor.pct(50), Glamor.px(45)), /* tuple */[
              "padding",
              "10% 50% 45px"
            ]);
        TestHelpers.testDeclaration(Glamor.padding4(Glamor.pct(10), Glamor.pct(50), Glamor.px(45), Glamor.ex(2)), /* tuple */[
              "padding",
              "10% 50% 45px 2ex"
            ]);
        TestHelpers.testDeclaration(Glamor.paddingTop(Glamor.px(1)), /* tuple */[
              "paddingTop",
              "1px"
            ]);
        TestHelpers.testDeclaration(Glamor.paddingRight(Glamor.px(1)), /* tuple */[
              "paddingRight",
              "1px"
            ]);
        TestHelpers.testDeclaration(Glamor.paddingBottom(Glamor.px(1)), /* tuple */[
              "paddingBottom",
              "1px"
            ]);
        return TestHelpers.testDeclaration(Glamor.paddingLeft(Glamor.px(1)), /* tuple */[
                    "paddingLeft",
                    "1px"
                  ]);
      }));

/*  Not a pure module */
