// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Glamor      = require("../src/Glamor.bs.js");
var TestHelpers = require("./TestHelpers.bs.js");

TestHelpers.testDeclaration(Glamor.color(Glamor.lemonchiffon), /* tuple */[
      "color",
      "lemonchiffon"
    ]);

TestHelpers.testDeclaration(Glamor.background(Glamor.none), /* tuple */[
      "background",
      "none"
    ]);

TestHelpers.testDeclaration(Glamor.background(Glamor.salmon), /* tuple */[
      "background",
      "salmon"
    ]);

TestHelpers.testDeclaration(Glamor.background(Glamor.url("foo")), /* tuple */[
      "background",
      "url(foo)"
    ]);

TestHelpers.testDeclaration(Glamor.backgroundColor(Glamor.peachpuff), /* tuple */[
      "backgroundColor",
      "peachpuff"
    ]);

TestHelpers.testDeclaration(Glamor.backgroundImage(Glamor.none), /* tuple */[
      "backgroundImage",
      "none"
    ]);

TestHelpers.testDeclaration(Glamor.backgroundImage(Glamor.url("foo")), /* tuple */[
      "backgroundImage",
      "url(foo)"
    ]);

TestHelpers.testDeclaration(Glamor.backgroundRepeat(Glamor.repeatY), /* tuple */[
      "backgroundRepeat",
      "repeat-y"
    ]);

TestHelpers.testDeclaration(Glamor.backgroundAttachment(Glamor.fixed), /* tuple */[
      "backgroundAttachment",
      "fixed"
    ]);

TestHelpers.testDeclaration(Glamor.backgroundPosition(Glamor.unset), /* tuple */[
      "backgroundPosition",
      "unset"
    ]);

TestHelpers.testDeclaration(Glamor.backgroundPosition2(Glamor.left, Glamor.center), /* tuple */[
      "backgroundPosition",
      "left center"
    ]);

TestHelpers.testDeclaration(Glamor.backgroundPosition2(Glamor.pct(75), Glamor.px(2)), /* tuple */[
      "backgroundPosition",
      "75% 2px"
    ]);

/*  Not a pure module */
