// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Jest                    = require("@glennsl/bs-jest/src/jest.js");
var List                    = require("bs-platform/lib/js/list.js");
var Glamor__InternalHelpers = require("../src/Glamor__InternalHelpers.bs.js");

function asDeclaration(prim) {
  return prim;
}

function testDeclaration(decl, expected) {
  return Jest.test(JSON.stringify(decl), (function () {
                return Jest.Expect[/* toEqual */12](expected, Jest.Expect[/* expect */0](decl));
              }));
}

function testValue(value, expected) {
  return Jest.test(value, (function () {
                return Jest.Expect[/* toEqual */12](expected, Jest.Expect[/* expect */0](value));
              }));
}

function testSelector(selector, expected) {
  var decls$prime = expected[1];
  var k$prime = expected[0];
  var decls = selector[1];
  var k = selector[0];
  return Jest.test(k, (function () {
                return Jest.Expect[/* toEqual */12](/* tuple */[
                            k$prime,
                            Glamor__InternalHelpers.Declarations[/* toDict */0](List.map(asDeclaration, decls$prime))
                          ], Jest.Expect[/* expect */0](/* tuple */[
                                k,
                                decls
                              ]));
              }));
}

exports.testDeclaration = testDeclaration;
exports.testValue       = testValue;
exports.testSelector    = testSelector;
/* Jest Not a pure module */
