// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Jest   = require("@glennsl/bs-jest/src/jest.js");
var Glamor = require("../src/Glamor.bs.js");

Jest.test("basic", (function () {
        var css = Glamor.style(/* :: */[
              Glamor.margin(Glamor.auto),
              /* :: */[
                Glamor.padding(Glamor.em(10)),
                /* :: */[
                  Glamor.margin(Glamor.unset),
                  /* [] */0
                ]
              ]
            ]);
        return Jest.Expect[/* toEqual */12]({
                    margin: "10em"
                  }, Jest.Expect[/* expect */0](css));
      }));

/*  Not a pure module */
