// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Jest                  = require("@glennsl/bs-jest/src/jest.js");
var Js_dict               = require("bs-platform/lib/js/js_dict.js");
var Caml_missing_polyfill = require("bs-platform/lib/js/caml_missing_polyfill.js");

function testDeclaration(decl, expected) {
  return Jest.test(Caml_missing_polyfill.not_implemented("JSON.stringify not implemented by bucklescript yet\n"), (function () {
                return Jest.Expect[/* toEqual */12](Js_dict.fromList(/* :: */[
                                expected,
                                /* [] */0
                              ]), Jest.Expect[/* expect */0](Js_dict.fromList(/* :: */[
                                    decl,
                                    /* [] */0
                                  ])));
              }));
}

function testValue(value, expected) {
  return Jest.test(value, (function () {
                return Jest.Expect[/* toEqual */12](expected, Jest.Expect[/* expect */0](value));
              }));
}

exports.testDeclaration = testDeclaration;
exports.testValue       = testValue;
/* Jest Not a pure module */
