// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Jest   = require("@glennsl/bs-jest/src/jest.js");
var Glamor = require("../src/Glamor.bs.js");

Jest.test("basic", (function () {
        var style = Glamor.css(/* :: */[
              Glamor.padding(Glamor.em(10)),
              /* :: */[
                Glamor.margin2(Glamor.zero, Glamor.auto),
                /* :: */[
                  Glamor.marginLeft(Glamor.initial),
                  /* [] */0
                ]
              ]
            ]);
        return Jest.Expect[/* toEqual */12]({
                    padding: "10em",
                    margin: "0 auto",
                    marginLeft: "initial"
                  }, Jest.Expect[/* expect */0](style));
      }));

/*  Not a pure module */
