// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Jest    = require("@glennsl/bs-jest/src/jest.js");
var Glamor  = require("../src/Glamor.bs.js");
var Js_dict = require("bs-platform/lib/js/js_dict.js");

function testDeclaration(decl, expected) {
  return Jest.test(JSON.stringify(decl), (function () {
                return Jest.Expect[/* toEqual */12](Js_dict.fromList(/* :: */[
                                expected,
                                /* [] */0
                              ]), Jest.Expect[/* expect */0](Glamor.css(/* :: */[
                                    decl,
                                    /* [] */0
                                  ])));
              }));
}

exports.testDeclaration = testDeclaration;
/* Jest Not a pure module */
