// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Glamor      = require("../src/Glamor.bs.js");
var TestHelpers = require("./TestHelpers.bs.js");

describe("transitionProperty", (function () {
        TestHelpers.testDeclaration(Glamor.transitionProperty(Glamor.unset), /* tuple */[
              "transitionProperty",
              "unset"
            ]);
        TestHelpers.testDeclaration(Glamor.transitionProperty(Glamor.none), /* tuple */[
              "transitionProperty",
              "none"
            ]);
        TestHelpers.testDeclaration(Glamor.transitionProperty(Glamor.AnimatableProperty[/* all */0]), /* tuple */[
              "transitionProperty",
              "all"
            ]);
        TestHelpers.testDeclaration(Glamor.transitionProperty(Glamor.AnimatableProperty[/* color */31]), /* tuple */[
              "transitionProperty",
              "color"
            ]);
        TestHelpers.testDeclaration(Glamor.transitionProperty(Glamor.ident("foo")), /* tuple */[
              "transitionProperty",
              "foo"
            ]);
        TestHelpers.testDeclaration(Glamor.transitionProperties(/* :: */[
                  Glamor.AnimatableProperty[/* all */0],
                  /* :: */[
                    Glamor.AnimatableProperty[/* color */31],
                    /* :: */[
                      Glamor.ident("foo"),
                      /* [] */0
                    ]
                  ]
                ]), /* tuple */[
              "transitionProperty",
              "all, color, foo"
            ]);
        return TestHelpers.testDeclaration(Glamor.transitionProperties(/* [] */0), /* tuple */[
                    "transitionProperty",
                    "none"
                  ]);
      }));

describe("transitionDuration", (function () {
        TestHelpers.testDeclaration(Glamor.transitionDuration(Glamor.unset), /* tuple */[
              "transitionDuration",
              "unset"
            ]);
        TestHelpers.testDeclaration(Glamor.transitionDuration(Glamor.s(3.2)), /* tuple */[
              "transitionDuration",
              "3.2s"
            ]);
        TestHelpers.testDeclaration(Glamor.transitionDurations(/* :: */[
                  Glamor.s(3.2),
                  /* :: */[
                    Glamor.ms(400),
                    /* [] */0
                  ]
                ]), /* tuple */[
              "transitionDuration",
              "3.2s, 400ms"
            ]);
        return TestHelpers.testDeclaration(Glamor.transitionDurations(/* [] */0), /* tuple */[
                    "transitionDuration",
                    ""
                  ]);
      }));

describe("transitionTimingFunction", (function () {
        TestHelpers.testDeclaration(Glamor.transitionTimingFunction(Glamor.unset), /* tuple */[
              "transitionTimingFunction",
              "unset"
            ]);
        TestHelpers.testDeclaration(Glamor.transitionTimingFunction(Glamor.linear), /* tuple */[
              "transitionTimingFunction",
              "linear"
            ]);
        TestHelpers.testDeclaration(Glamor.transitionTimingFunctions(/* :: */[
                  Glamor.linear,
                  /* :: */[
                    Glamor.easeIn,
                    /* [] */0
                  ]
                ]), /* tuple */[
              "transitionTimingFunction",
              "linear, ease-in"
            ]);
        return TestHelpers.testDeclaration(Glamor.transitionTimingFunctions(/* [] */0), /* tuple */[
                    "transitionTimingFunction",
                    ""
                  ]);
      }));

describe("transitionDelay", (function () {
        TestHelpers.testDeclaration(Glamor.transitionDelay(Glamor.unset), /* tuple */[
              "transitionDelay",
              "unset"
            ]);
        TestHelpers.testDeclaration(Glamor.transitionDelay(Glamor.ms(100)), /* tuple */[
              "transitionDelay",
              "100ms"
            ]);
        TestHelpers.testDeclaration(Glamor.transitionDelays(/* :: */[
                  Glamor.s(3.2),
                  /* :: */[
                    Glamor.ms(100),
                    /* [] */0
                  ]
                ]), /* tuple */[
              "transitionDelay",
              "3.2s, 100ms"
            ]);
        return TestHelpers.testDeclaration(Glamor.transitionDelays(/* [] */0), /* tuple */[
                    "transitionDelay",
                    ""
                  ]);
      }));

describe("transition", (function () {
        TestHelpers.testDeclaration(Glamor.transition(Glamor.unset), /* tuple */[
              "transition",
              "unset"
            ]);
        TestHelpers.testDeclaration(Glamor.transition(Glamor.none), /* tuple */[
              "transition",
              "none"
            ]);
        TestHelpers.testDeclaration(Glamor.transitions(/* :: */[
                  /* tuple */[
                    Glamor.AnimatableProperty[/* top */100],
                    Glamor.ms(100),
                    Glamor.linear,
                    Glamor.s(1)
                  ],
                  /* :: */[
                    /* tuple */[
                      Glamor.AnimatableProperty[/* left */54],
                      Glamor.ms(200),
                      Glamor.easeIn,
                      Glamor.ms(50)
                    ],
                    /* [] */0
                  ]
                ]), /* tuple */[
              "transition",
              "top 100ms linear 1s, left 200ms ease-in 50ms"
            ]);
        return TestHelpers.testDeclaration(Glamor.transitions(/* [] */0), /* tuple */[
                    "transition",
                    "none"
                  ]);
      }));

/*  Not a pure module */
