// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Glamor      = require("../src/Glamor.bs.js");
var TestHelpers = require("./TestHelpers.bs.js");

describe("universal", (function () {
        TestHelpers.testValue(Glamor.inherit_, "inherit");
        TestHelpers.testValue(Glamor.initial, "initial");
        return TestHelpers.testValue(Glamor.unset, "unset");
      }));

describe("shared", (function () {
        TestHelpers.testValue(Glamor.none, "none");
        return TestHelpers.testValue(Glamor.auto, "auto");
      }));

describe("length", (function () {
        TestHelpers.testValue(Glamor.em(1.5), "1.5em");
        TestHelpers.testValue(Glamor.ex(1), "1ex");
        TestHelpers.testValue(Glamor.inch(1), "1in");
        TestHelpers.testValue(Glamor.cm(1), "1cm");
        TestHelpers.testValue(Glamor.mm(1), "1mm");
        TestHelpers.testValue(Glamor.pt(1), "1pt");
        TestHelpers.testValue(Glamor.pc(1), "1pc");
        TestHelpers.testValue(Glamor.px(1), "1px");
        return TestHelpers.testValue(Glamor.zero, "0");
      }));

describe("percentage", (function () {
        return TestHelpers.testValue(Glamor.pct(1.2), "1.2%");
      }));

describe("url", (function () {
        return TestHelpers.testValue(Glamor.url("harry potter"), "url(harry potter)");
      }));

/*  Not a pure module */
